version: '3.8'

services:
  web:
    build: .
    command: uvicorn presentation.api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
     

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    env_file:
      - .env

volumes:
  postgres_data:
